spring:
  datasource:
    url: jdbc:mysql://localhost:3306/borgosesia_lm
    username: root
    password: m194asto
server:
  port: 8280
logging:
  level:
    root: INFO
  file:
    name: /var/log/xplants/borgosesia-lm.log
    path: /var/log/xplants
remote:
  auth:
    url: http://localhost:2005/Apps/WebObjects/borgosesia.woa/wa/UserAction/authenticate
bgs:
  default: 
    repository: /var/www/bgs.repository